name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.18'

      - name: Install dependencies
        run: go mod download

      - name: Run unit tests
        run: go test -v ./tests/unit/...

      - name: Run integration tests
        run: go test -v ./tests/integration/...